### ISSUE TITLE
Error: EEXIST, file already exists

### ISSUE THREAD

**Issue by JDillon522** [ember-cli/broccoli-caching-writer#34]
I recently started getting this error whenever I added [ember-cli-compass-compiler](https://github.com/quaertym/ember-cli-compass-compiler) to my project. It pops up every time I try to save a file and it kills everything. I dont know if the issue originates here, but it after the [symlink-copy](https://www.npmjs.com/package/symlink-or-copy) stack trace. 

I have an [open thread on the discuss ember board](http://discuss.emberjs.com/t/import-scss-files-from-outside-project-structure/7445/3)

```
EEXIST, file already exists '/Users/jdillon/Documents/.../app/tmp/class-tmp_cache_dir-SjogQwVL.tmp'
Error: EEXIST, file already exists '/Users/jdillon/Documents/.../app/tmp/class-tmp_cache_dir-SjogQwVL.tmp'
    at Object.fs.symlinkSync (fs.js:741:18)
    at symlink (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)
    at Function.symlinkOrCopySync [as sync] (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at /Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:103:21
    at lib$rsvp$$internal$$tryCatch (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/jdillon/Documents/.../app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I'm not sure if this should be reported here or somewhere else.

**Comment by JDillon522** [comment]
nevermind. I'm going to post this over at https://github.com/broccolijs/node-symlink-or-copy. Brain isnt working.
