### ISSUE TITLE
Conflicts with newer version of lodash

### ISSUE THREAD

**Issue by shunchu** [ember-cli/broccoli-caching-writer#35]
When installing a newer version of `lodash` (tested with v3.5.0) for use with Ember (v1.10.0) + broccoli-sass (v0.4.0), running `ember s` blows up with the following error:

```bash
Path or pattern "bower_components/lodash/dist/lodash.min.js" did not match any files
Error: Path or pattern "bower_components/lodash/dist/lodash.min.js" did not match any files
    at Object.multiGlob (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/someUser/Sites/projectName/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by shunchu** [comment]
My bad. An older version of `ember-cli-lodash` was installed. Uninstalling it made the issue go away.
